FROM python:3.9

WORKDIR /root/git

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements-release.txt

# Build the wheel
RUN python setup.py sdist bdist_wheel